name: Build
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    name: node${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up npm 8
        run: npm i -g npm@8

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
    env:
      CI: true

  summary:
    runs-on: ubuntu-latest
    needs:
      - build

    if: always()

    name: build-summary

    steps:
      - name: Build status
        run: if ${{ needs.build.result != 'success' && needs.build.result != 'skipped' }}; then exit 1; fi
