name: JS Tests
on: pull_request

jobs:
  jest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]
        npm-version: [8]
        include:
          - node-version: 14
            npm-version: 7

    name: node${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up npm ${{ matrix.npm-version }}
        run: npm i -g npm@${{ matrix.npm-version }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage-final.json
          flags: javascript
          fail_ci_if_error: true

  summary:
    runs-on: ubuntu-latest
    needs:
      - jest

    if: always()

    name: npm-test-summary

    steps:
      - name: Jest status
        run: if ${{ needs.jest.result != 'success' && needs.jest.result != 'skipped' }}; then exit 1; fi
